/* Lasers 3D - shipped level set (DESIGN.md 3.7). Generated by tools/gen-batches.mjs - edit that, not this.
 * UMD: browser global `LASER_LEVELS`, CommonJS `module.exports`. Data only. ES2019 (Safari 15).
 *
 * SCHEMA (INTERFACES.md section 3, plus the `solution` extension of INTERFACES-FRONTEND.md section 7):
 *   {
 *     name:     'FIRST BOUNCE',              // display name, short, all caps, unique
 *     par:      1,                           // minimum piece count, PROVEN by an exhaustive search at depth par-1
 *     size:     { w: 12, d: 12 },            // w cells east-west (x), d cells north-south (y); 12..24
 *     terrain:  ['000000', ...],             // d strings of w chars '0'..'3' = height; terrain[y][x]; y = 0 is the SOUTH row
 *     openings: [{ x, y, levels: [0] }],     // OPTIONAL (DESIGN.md 13): levels punched OUT of a column, each
 *                                            // an integer 0..3 strictly below that column's terrain height.
 *                                            // levels [0] under a tall column = an ARCH (go under it);
 *                                            // a middle level = a WINDOW (thread it at that height only).
 *                                            // Identical to a solid column from directly above - that is the point.
 *     emitter:  { x: 0, y: 2, dir: 'E' },    // dir in E N W S; fires level (pitch 0) at height terrain[y][x]
 *     targets:  [{ x: 3, y: 5 }],            // 1 or 2 orbs; an orb sits at height terrain[y][x]; all must be lit
 *     fixed:    [{ x, y, type, orient, secret }], // immovable pieces; secret = drawn as a plain mirror in the flat view
 *     tray:     ['MIRROR', ...],             // inventory; par <= tray.length <= par + 1
 *     intro:    '',                          // one-line teaching text, shown once (only teaching levels have one)
 *     dark:     true,                        // OPTIONAL (DESIGN.md 15): fog of war. Terrain, pieces, targets and
 *                                            // openings are drawn only where a beam has been; discovery accumulates
 *                                            // and RESET never takes it away. A rendering flag - the rules engine
 *                                            // ignores it. Late levels only, never a teaching level (15.3).
 *     solution: [{ x, y, type, orient }]     // one proven minimal solution (length == par); used ONLY by the hint
 *   }
 * Boards run 12x12 (levels 1-3) to 24x24 (levels 21-23); the renderer auto-zooms and pans when a cell would
 * fall under the 34 px touch floor. Levels 1-3 are pure 2D (heights 0/3, MIRROR only). Every level from 4 on
 * is 3D-necessary (validate-levels.mjs).
 * Pieces: MIRROR turns and keeps the climb, WEDGE turns and tilts up, DIP turns and tilts down, and FLOOR
 * (DESIGN.md 14) does NOT turn at all - it lies flat and throws a falling beam back up on the same heading.
 * Map comments: north row first; . = floor, 1-3 = height, > ^ < v = emitter, @ = target, F = fixed piece,
 * A = a full-height column with an ARCH under it (open at level 0), O = one with a WINDOW in it (open above 0).
 * Verify: node validate-levels.mjs
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.LASER_LEVELS = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return [
  // 1. FIRST BOUNCE  (12x12, par 1, seed 21)
  //   y=11  . . @ . 3 . . . . . . .
  //   y=10  . . . . . . . . . . 3 3
  //   y= 9  . . . . . . . . . . 3 3
  //   y= 8  3 3 . . . . . . . . 3 3
  //   y= 7  3 3 . . . . . . . . 3 3
  //   y= 6  3 3 . . . . . . . . . .
  //   y= 5  . 3 . 3 . . . . . . . .
  //   y= 4  . 3 . 3 . . . 3 3 3 3 .
  //   y= 3  . 3 . . . . . . . . . <
  //   y= 2  . . . . . . . . . . . .
  //   y= 1  . . . . . . . . . . . .
  //   y= 0  . . . . . . . . . 3 3 3
  {
    name: 'FIRST BOUNCE',
    par: 1,
    size: { w: 12, d: 12 },
    terrain: ['000000000333', '000000000000', '000000000000', '030000000000', '030300033330', '030300000000', '330000000000', '330000000033', '330000000033', '000000000033', '000000000033', '000030000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 11, y: 3, dir: 'W' },
    targets: [{ x: 2, y: 11 }],
    fixed: [],
    tray: ['MIRROR', 'MIRROR'],
    intro: 'Tap a square to put a mirror down. Tap it again to spin it. Then hit FIRE.',
    solution: [{ x: 2, y: 3, type: 'MIRROR', orient: '\\' }],
  },

  // 2. AROUND THE CORNER  (12x12, par 1, seed 34)
  //   y=11  . . . . . . . . 3 . . 3
  //   y=10  . . . . . . . . 3 . . .
  //   y= 9  . . . . . . . . 3 . . .
  //   y= 8  . @ . . . . . . . . . .
  //   y= 7  . . . . . 3 . . . . 3 .
  //   y= 6  . . 3 . . 3 . . . . 3 .
  //   y= 5  . . 3 3 3 3 . . . . 3 .
  //   y= 4  3 . 3 3 3 3 . . . . 3 .
  //   y= 3  3 . 3 3 3 3 . . . . 3 .
  //   y= 2  3 . 3 3 3 3 . . . . . .
  //   y= 1  3 . . . . . . . . . . .
  //   y= 0  . . . . . . . . . ^ . .
  {
    name: 'AROUND THE CORNER',
    par: 1,
    size: { w: 12, d: 12 },
    terrain: ['000000000000', '300000000000', '303333000000', '303333000030', '303333000030', '003333000030', '003003000030', '000003000030', '000000000000', '000000003000', '000000003000', '000000003003'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 9, y: 0, dir: 'N' },
    targets: [{ x: 1, y: 8 }],
    fixed: [],
    tray: ['MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 9, y: 8, type: 'MIRROR', orient: '\\' }],
  },

  // 3. DOUBLE TAKE  (12x12, par 2, seed 40)
  //   y=11  . . . @ . 3 . . . . . .
  //   y=10  . . . . . . . . . . . .
  //   y= 9  . . . . . . . . . . . .
  //   y= 8  . . . . . . 3 3 3 . . 3
  //   y= 7  . . . . . . 3 3 3 . . .
  //   y= 6  . . . . . . 3 3 3 . . .
  //   y= 5  . . . . . . . . . . . .
  //   y= 4  . . . . . . . . . . . .
  //   y= 3  . . . . . . 3 3 3 . . .
  //   y= 2  . . 3 3 3 3 3 3 3 . . .
  //   y= 1  . . . . . . 3 3 3 . . .
  //   y= 0  . . . . . . . . . ^ . .
  {
    name: 'DOUBLE TAKE',
    par: 2,
    size: { w: 12, d: 12 },
    terrain: ['000000000000', '000000333000', '003333333000', '000000333000', '000000000000', '000000000000', '000000333000', '000000333000', '000000333003', '000000000000', '000000000000', '000003000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 9, y: 0, dir: 'N' },
    targets: [{ x: 3, y: 11 }],
    fixed: [],
    tray: ['MIRROR', 'MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 9, y: 9, type: 'MIRROR', orient: '\\' }, { x: 3, y: 9, type: 'MIRROR', orient: '\\' }],
  },

  // 4. OVER THE WALL  (14x14, par 2, seed 41)
  //   y=13  1 . . . . . . v 2 . . . . .
  //   y=12  . . . . . . . . 3 3 . . . .
  //   y=11  . . . . . 3 3 1 . . . . . .
  //   y=10  . . 2 2 2 . . 1 . . . . . .
  //   y= 9  . . 2 2 2 . . 1 . . . . . .
  //   y= 8  . . 2 2 2 . . 1 1 2 2 . . .
  //   y= 7  . . 2 2 2 . . 1 1 2 2 . . .
  //   y= 6  3 . . . . . . . . . . . . .
  //   y= 5  3 2 2 2 2 2 2 . . . . . . .
  //   y= 4  3 . . . . . . . 3 3 3 3 . .
  //   y= 3  3 . 1 2 2 2 2 . 3 3 3 3 3 .
  //   y= 2  1 . 1 1 1 1 1 1 3 3 3 3 . .
  //   y= 1  . . 1 1 . . . . . . . . . .
  //   y= 0  @ . 1 1 . . . 2 . . . . . .
  {
    name: 'OVER THE WALL',
    par: 2,
    size: { w: 14, d: 14 },
    terrain: ['10110002000000', '00110000000000', '10111111333300', '30122220333330', '30000000333300', '32222220000000', '30000000000000', '00222001122000', '00222001122000', '00222001000000', '00222001000000', '00000331000000', '00000000330000', '10000001200000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 7, y: 13, dir: 'S' },
    targets: [{ x: 0, y: 0 }],
    fixed: [],
    tray: ['MIRROR', 'MIRROR', 'MIRROR'],
    intro: 'Some walls are lower than they look, and a beam can fly right over a low one. The beam gets wider and brighter the higher it climbs, and the readout after FIRE names every height. You can tilt the board to peek, but a no-tilt solve is what earns the third star.',
    solution: [{ x: 7, y: 2, type: 'MIRROR', orient: '/' }, { x: 0, y: 2, type: 'MIRROR', orient: '/' }],
  },

  // 5. UP THE STAIRS  (14x14, par 2, seed 73)
  //   y=13  3 3 3 3 . . . . . . @ . 1 .
  //   y=12  3 3 3 3 . . . . . . . 1 1 .
  //   y=11  . . . . . . . 3 3 3 1 . 1 .
  //   y=10  . . . . . . . 3 3 3 3 . . .
  //   y= 9  3 3 3 . . . . 3 3 3 3 . . .
  //   y= 8  3 3 3 . . . . 2 . . . . 3 3
  //   y= 7  3 3 3 . . 1 1 2 1 1 1 . 2 .
  //   y= 6  . . . . . 1 1 2 . . . . . .
  //   y= 5  . . . . . 3 3 3 3 3 . . . .
  //   y= 4  . . . . . 1 1 1 . . . . . .
  //   y= 3  . . . 1 . 1 1 1 . . 1 . 1 1
  //   y= 2  . . . 1 1 . . . . . . . . .
  //   y= 1  . . . 1 . . . . . . . . . .
  //   y= 0  . . . 1 . 2 2 2 . . . ^ . .
  {
    name: 'UP THE STAIRS',
    par: 2,
    size: { w: 14, d: 14 },
    terrain: ['00010222000000', '00010000000000', '00011000000000', '00010111001011', '00000111000000', '00000333330000', '00000112000000', '33300112111020', '33300002000033', '33300003333000', '00000003333000', '00000003331010', '33330000000110', '33330000003010'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 11, y: 0, dir: 'N' },
    targets: [{ x: 10, y: 13 }],
    fixed: [],
    tray: ['WEDGE', 'MIRROR', 'MIRROR'],
    intro: 'A WEDGE turns the beam and tilts it UP one step every square. A plain mirror turns it too, but it keeps the beam climbing - watch it grow brighter as it rises.',
    solution: [{ x: 11, y: 11, type: 'WEDGE', orient: '\\' }, { x: 10, y: 11, type: 'MIRROR', orient: '\\' }],
  },

  // 6. BEND THEN CLIMB  (14x14, par 2, seed 74)
  //   y=13  . . . 2 2 2 2 2 . . . . 1 2
  //   y=12  > . . . . . . . . . 2 2 1 2
  //   y=11  . 1 . . 1 1 1 . 2 . . . 1 2
  //   y=10  . 1 . . . 1 . . 3 . . . 1 2
  //   y= 9  . 1 . . . . . . 3 . . . 1 2
  //   y= 8  . 1 . . . . . . 2 . . . 2 2
  //   y= 7  . 1 . . . . . . 2 . . . 1 2
  //   y= 6  . . . . . . . . 2 . 1 . . 2
  //   y= 5  . . . . . . . 3 3 . 3 . . 3
  //   y= 4  . 2 2 2 2 . . . 1 . 1 1 @ 3
  //   y= 3  . 3 3 3 3 . . . . 1 . . . 3
  //   y= 2  . 3 3 3 3 . . . . . . . . .
  //   y= 1  . 3 3 3 3 . . . . . . . . 1
  //   y= 0  . 3 3 3 3 . . . . . . . . .
  {
    name: 'BEND THEN CLIMB',
    par: 2,
    size: { w: 14, d: 14 },
    terrain: ['03333000000000', '03333000000001', '03333000000000', '03333000010003', '02222000101133', '00000003303003', '00000000201002', '01000000200012', '01000000200022', '01000000300012', '01000100300012', '01001110200012', '00000000002212', '00022222000012'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 0, y: 12, dir: 'E' },
    targets: [{ x: 12, y: 4 }],
    fixed: [],
    tray: ['MIRROR', 'WEDGE', 'MIRROR'],
    intro: '',
    solution: [{ x: 9, y: 12, type: 'MIRROR', orient: '\\' }, { x: 9, y: 4, type: 'WEDGE', orient: '\\' }],
  },

  // 7. LEVEL OFF  (16x16, par 3, seed 74)
  //   y=15  . . . . . . . . . . . 3 . . . 2
  //   y=14  > . . . . . . . . . . 3 3 3 3 2
  //   y=13  . . . . . . . . 1 . . 3 3 3 3 2
  //   y=12  . . . . . . . . 1 3 . . 3 3 3 2
  //   y=11  . . . . . . . . 3 . 3 2 3 3 3 3
  //   y=10  . . . . . . . . 3 3 3 3 . . 1 .
  //   y= 9  . . . . . . . . 3 3 . 3 . . 1 .
  //   y= 8  . . . . . . . . . . . 3 1 1 1 .
  //   y= 7  . . . . . . . 2 2 2 . 3 1 1 . .
  //   y= 6  . . . . . . . 2 3 3 3 3 1 . 1 3
  //   y= 5  2 2 2 2 . . . 2 2 2 . 3 1 . . 3
  //   y= 4  2 2 2 2 . . 1 2 2 2 . . 1 . . 3
  //   y= 3  2 2 3 3 3 3 . . . . . . 1 . . .
  //   y= 2  2 2 3 3 3 3 . . . . . . 1 . . .
  //   y= 1  . . 3 3 3 3 . . . . . . . . . @
  //   y= 0  . . 3 3 3 3 . . . . . . . . . 3
  {
    name: 'LEVEL OFF',
    par: 3,
    size: { w: 16, d: 16 },
    terrain: ['0033330000000003', '0033330000000003', '2233330000001000', '2233330000001000', '2222001222001003', '2222000222031003', '0000000233331013', '0000000222031100', '0000000000031110', '0000000033030010', '0000000033330010', '0000000030323333', '0000000013003332', '0000000010033332', '0000000000033332', '0000000000030002'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 0, y: 14, dir: 'E' },
    targets: [{ x: 15, y: 1 }],
    fixed: [],
    tray: ['WEDGE', 'DIP', 'MIRROR', 'MIRROR'],
    intro: 'A DIP turns the beam and tilts it DOWN one step. That makes it the only thing that can flatten a climbing beam: go UP with a wedge, then DIP to level off and fly straight.',
    solution: [{ x: 8, y: 14, type: 'WEDGE', orient: '\\' }, { x: 8, y: 11, type: 'DIP', orient: '\\' }, { x: 15, y: 11, type: 'MIRROR', orient: '\\' }],
  },

  // 8. ON STILTS  (16x16, par 3, seed 84)
  //   y=15  . 3 1 1 1 1 1 1 1 . . . . . 2 .
  //   y=14  . 3 . 2 2 1 . 2 2 . . . . 1 2 3
  //   y=13  . 3 . . . . . . . . . . . . . <
  //   y=12  . 3 . . . . . 3 3 3 1 3 3 3 3 3
  //   y=11  . 3 . . . 2 3 3 3 3 . 3 3 3 . 3
  //   y=10  . 3 . . . . . 3 3 3 . . . . . 3
  //   y= 9  . 3 1 1 1 1 . . . . . . . . . .
  //   y= 8  . 3 1 1 1 . . . . . 3 3 3 . 3 3
  //   y= 7  . 3 1 1 1 . 3 . . . 3 3 3 . . .
  //   y= 6  . 3 1 1 1 . 3 . 3 . 3 3 3 . . .
  //   y= 5  . 3 . . . . 2 . 3 . 3 3 3 . . .
  //   y= 4  . 3 3 . . . 3 . 3 . . . . . . 2
  //   y= 3  . . . . . . . . 3 . . . . . . .
  //   y= 2  . . . . . . . . 3 . . . . . . .
  //   y= 1  . . . . . . . . . . . . . 2 . .
  //   y= 0  . . . . . . @ . . . . . . . . .
  {
    name: 'ON STILTS',
    par: 3,
    size: { w: 16, d: 16 },
    terrain: ['0000003000000000', '0000000000000200', '0000000030000000', '0000000030000000', '0330003030000002', '0300002030333000', '0311103030333000', '0311103000333000', '0311100000333033', '0311110000000000', '0300000333000003', '0300023333033303', '0300000333133333', '0300000000000000', '0302210220000123', '0311111110000020'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 15, y: 13, dir: 'W' },
    targets: [{ x: 6, y: 0 }],
    fixed: [],
    tray: ['WEDGE', 'MIRROR', 'DIP', 'MIRROR'],
    intro: 'You can stand a piece on top of a block. Only a beam at that same height will hit it, and the readout after FIRE tells you what height your beam is flying at.',
    solution: [{ x: 5, y: 13, type: 'WEDGE', orient: '/' }, { x: 5, y: 11, type: 'MIRROR', orient: '\\' }, { x: 6, y: 11, type: 'DIP', orient: '\\' }],
  },

  // 9. SECRET RAMP  (16x16, par 3, seed 97)
  //   y=15  . 2 . . . . . . . . . . . . . .
  //   y=14  . 2 3 3 3 . . . . . . . . . . .
  //   y=13  . 2 3 3 3 . . . . . . . . . 2 2
  //   y=12  . 2 3 3 3 3 3 3 3 3 3 3 3 3 . .
  //   y=11  . 2 2 2 2 2 2 2 2 2 . 3 3 3 . .
  //   y=10  . 2 . . . . . . . . . . @ 3 . .
  //   y= 9  . . . . . . . . . . . . . 1 . .
  //   y= 8  . . . . . . . . . . . . . . . .
  //   y= 7  . . . . . . 3 3 3 3 3 3 . 3 3 .
  //   y= 6  . . . 1 F 1 1 3 . . . 2 . 2 2 2
  //   y= 5  . . 1 . . 1 1 2 . 3 3 3 . 3 3 3
  //   y= 4  . 3 . . . 1 1 3 . . . 3 . . . .
  //   y= 3  . . . 3 . 3 3 3 . . . . . . . .
  //   y= 2  1 . . . . 1 3 . 2 2 2 2 . . . .
  //   y= 1  . . . . . . 3 3 . . . . 3 . . .
  //   y= 0  . . . . ^ . 3 3 . 3 3 3 3 . . .
  {
    name: 'SECRET RAMP',
    par: 3,
    size: { w: 16, d: 16 },
    terrain: ['0000003303333000', '0000003300003000', '1000013022220000', '0003033300000000', '0300011300030000', '0010011203330333', '0001011300020222', '0000003333330330', '0000000000000000', '0000000000000100', '0200000000003300', '0222222222033300', '0233333333333300', '0233300000000022', '0233300000000000', '0200000000000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 4, y: 0, dir: 'N' },
    targets: [{ x: 12, y: 10 }],
    fixed: [{ x: 4, y: 6, type: 'WEDGE', orient: '/', secret: true }],
    tray: ['DIP', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: 'One of these mirrors is not a mirror. Fire and watch the beam: if it turns and starts climbing, you have found the hidden wedge - and only a DIP can bring it back down to level.',
    solution: [{ x: 7, y: 6, type: 'DIP', orient: '\\' }, { x: 7, y: 1, type: 'MIRROR', orient: '\\' }, { x: 12, y: 1, type: 'MIRROR', orient: '/' }],
  },

  // 10. UNDER THE ARCH  (18x18, par 3, seed 1006)
  //   y=17  . 3 1 1 1 . . . . . . . . . 3 . . 1
  //   y=16  . 3 1 1 2 2 2 . . . 2 . . . 3 . . 1
  //   y=15  . 3 . . 2 2 2 F . . . . . . A . . <
  //   y=14  . 3 . 1 2 2 2 . . . . . 2 2 3 3 3 .
  //   y=13  . 3 . 1 1 . . . . . . . 2 2 3 . . .
  //   y=12  1 3 1 1 1 . . . . . . . 2 2 . . . .
  //   y=11  1 3 1 1 1 3 3 . . . 1 1 1 1 . . . .
  //   y=10  3 3 1 1 . 3 3 . 2 2 2 2 2 2 2 . . .
  //   y= 9  3 3 1 1 . 3 3 . . . . . 1 1 . . . .
  //   y= 8  3 3 . . . . . . . 1 . . . 3 3 3 . .
  //   y= 7  . . . . . . . . 2 2 . . . 3 3 3 . .
  //   y= 6  . 1 . . . . . . 2 2 . . . 3 3 3 2 .
  //   y= 5  . . . . . . . 1 2 3 3 . . 1 2 2 2 .
  //   y= 4  . . . . . . . . 2 2 . . . 1 2 2 2 .
  //   y= 3  . @ . . . . . . . . . . . . 2 2 2 .
  //   y= 2  . . . . . . . . . 1 . . . . . . . .
  //   y= 1  . . . . . . . . 1 1 1 . . . . . . .
  //   y= 0  . . . . . . . . 1 1 1 . . . . . . .
  {
    name: 'UNDER THE ARCH',
    par: 3,
    size: { w: 18, d: 18 },
    terrain: ['000000001110000000', '000000001110000000', '000000000100000000', '000000000000002220', '000000002200012220', '000000012330012220', '010000002200033320', '000000002200033300', '330000000100033300', '331103300000110000', '331103302222222000', '131113300011110000', '131110000000220000', '030110000000223000', '030122200000223330', '030022200000003000', '031122200020003001', '031110000000003001'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 14, y: 15, levels: [0] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 17, y: 15, dir: 'W' },
    targets: [{ x: 1, y: 3 }],
    fixed: [{ x: 7, y: 15, type: 'MIRROR', orient: '/', secret: false }],
    tray: ['MIRROR', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: 'Look for the faint sliver of light on the floor - that block is not solid all the way down. A beam at ground level slips straight under it, and the readout after FIRE always names the height your beam is flying at.',
    solution: [{ x: 7, y: 9, type: 'MIRROR', orient: '\\' }, { x: 11, y: 9, type: 'MIRROR', orient: '\\' }, { x: 11, y: 3, type: 'MIRROR', orient: '/' }],
  },

  // 11. THROUGH THE WINDOW  (18x18, par 2, seed 1116)
  //   y=17  . . . 2 . . . . . 2 @ 2 2 2 2 . . .
  //   y=16  . . . 2 . . . . . . 1 . . . . . . .
  //   y=15  . . . 2 . . . 2 2 . 1 . . . . . . .
  //   y=14  . . . 2 . . . . . . . . 3 . . . . .
  //   y=13  . . . 2 . . . . 3 3 O 3 3 1 . . . .
  //   y=12  . . . 2 2 1 1 1 1 . 1 1 3 1 . . . .
  //   y=11  . . . 2 2 . . . . . 1 1 3 1 . . . .
  //   y=10  . . . 2 2 . . . . . 1 1 3 1 1 . . .
  //   y= 9  . . . . . . . . . 1 . . 3 . 1 . . .
  //   y= 8  . . . . . 1 . . . 1 3 3 3 . 1 . . .
  //   y= 7  . . . . . 1 . . . 1 . . . . 1 . . .
  //   y= 6  . . . . . . 3 3 . 1 . . . . 1 . . .
  //   y= 5  . . . . . . 3 3 . 1 . . . . 1 . . .
  //   y= 4  > . . 1 1 F 3 3 3 3 . . . . 1 . . .
  //   y= 3  1 1 . . 2 2 3 3 3 3 3 3 3 3 3 3 . .
  //   y= 2  1 1 . . 2 2 3 3 3 3 . . 3 3 3 3 . .
  //   y= 1  1 1 . . . . 3 3 3 3 1 1 1 1 1 1 . .
  //   y= 0  . . . . . . 2 2 . . . . . . . . . 2
  {
    name: 'THROUGH THE WINDOW',
    par: 2,
    size: { w: 18, d: 18 },
    terrain: ['000000220000000002', '110000333311111100', '110022333300333300', '110022333333333300', '100111333300001000', '000000330100001000', '000000330100001000', '000001000100001000', '000001000133301000', '000000000100301000', '000220000011311000', '000220000011310000', '000221111011310000', '000200003333310000', '000200000000300000', '000200022010000000', '000200000010000000', '000200000212222000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 10, y: 13, levels: [1] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 0, y: 4, dir: 'E' },
    targets: [{ x: 10, y: 17 }],
    fixed: [{ x: 5, y: 4, type: 'MIRROR', orient: '/', secret: false }],
    tray: ['MIRROR', 'MIRROR', 'MIRROR'],
    intro: 'This block is hollow part-way UP, not at the bottom. The floor leaks the same faint light, but only a beam already flying at the hole\'s height will thread it - the readout after FIRE names the height your beam is at.',
    solution: [{ x: 5, y: 12, type: 'MIRROR', orient: '/' }, { x: 10, y: 12, type: 'MIRROR', orient: '/' }],
  },

  // 12. TWO ORBS  (18x18, par 3, seed 140)
  //   y=17  . 2 2 2 2 1 1 . 3 . . 2 3 2 . 1 1 .
  //   y=16  . 2 2 2 2 1 1 . 3 . . 2 3 . . 1 1 .
  //   y=15  1 . . . . 1 1 . 3 . 1 2 3 1 . 1 1 .
  //   y=14  1 . . . . . . . 1 . . . 3 . . . . .
  //   y=13  1 . . . 3 3 3 . 1 . . . 3 . . . . .
  //   y=12  1 . . . . . . . 1 . . . 3 . . . . .
  //   y=11  1 2 2 . . . . . 3 3 2 2 3 . . . . .
  //   y=10  . 2 2 . . . . . 1 . 2 2 2 . . . . .
  //   y= 9  . 2 2 . . 3 3 . 1 . 2 2 2 . . 2 . .
  //   y= 8  . 2 . . . 3 3 1 1 1 2 2 2 1 . . . .
  //   y= 7  . 2 1 . . 3 3 . . . 2 . . . . . . .
  //   y= 6  2 2 1 1 . 3 3 . 3 3 3 3 . . . . . .
  //   y= 5  > . . . . . . . . F . . . . . . . .
  //   y= 4  2 2 . . . . . 3 3 . . . . . . . . 1
  //   y= 3  2 2 . . . . . 3 3 2 . . . . . . . .
  //   y= 2  . . . . . . . 3 @ 3 3 . . . . . . .
  //   y= 1  . . . . . . . . 3 . . . . . . . . .
  //   y= 0  . . . . . . . . 3 . . . . 3 3 2 2 @
  {
    name: 'TWO ORBS',
    par: 3,
    size: { w: 18, d: 18 },
    terrain: ['000000003000033223', '000000003000000000', '000000033330000000', '220000033200000000', '220000033000000001', '000000000000000000', '221103303333000000', '021003300020000000', '020003311122210000', '022003301022200200', '022000001022200000', '122000003322300000', '100000001000300000', '100033301000300000', '100000001000300000', '100001103012310110', '022221103002300110', '022221103002320110'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 0, y: 5, dir: 'E' },
    targets: [{ x: 8, y: 2 }, { x: 17, y: 0 }],
    fixed: [{ x: 9, y: 5, type: 'WEDGE', orient: '\\', secret: false }],
    tray: ['WEDGE', 'DIP', 'MIRROR', 'MIRROR'],
    intro: 'Two orbs this time. One beam has to light them both - it passes straight through the first one and carries on to the second.',
    solution: [{ x: 9, y: 3, type: 'WEDGE', orient: '/' }, { x: 8, y: 3, type: 'DIP', orient: '/' }, { x: 8, y: 0, type: 'MIRROR', orient: '\\' }],
  },

  // 13. SKIPPING STONE  (20x20, par 3, seed 1304)
  //   y=19  3 v 3 . . . . . . . . . . . . 2 1 . 3 .
  //   y=18  3 2 3 . 2 2 2 2 2 2 . . . . . . 1 . 3 .
  //   y=17  3 2 3 . . . . . . . . . . . . . . . 3 .
  //   y=16  . 2 . . . 3 3 . . . 2 2 2 . . . . . 3 .
  //   y=15  . 2 . . . 3 3 . . . 2 . . . . 2 2 . 3 .
  //   y=14  . 2 . . . 3 3 . . . . . . . . 1 . . 3 .
  //   y=13  . . . . . . . . 2 2 2 2 . . . 1 . . 3 .
  //   y=12  . . . . . . 2 2 2 2 2 2 1 . . 2 2 . 3 .
  //   y=11  . . . . . . 2 2 2 2 . . 1 . . 1 . . . .
  //   y=10  . . . . . . 2 2 2 2 . . 2 2 . 1 . . . .
  //   y= 9  . F 2 2 1 2 . . 2 2 . . 1 . . 1 . . . .
  //   y= 8  . . . . . . . . . . . 2 2 2 . 1 . . . .
  //   y= 7  . . . . . . . 1 . 1 . 2 2 2 . . . . . .
  //   y= 6  . . 2 . . . . . 1 . . 2 2 2 . . . . . .
  //   y= 5  . . . . . . . . 1 . . 2 2 2 . . 1 1 . .
  //   y= 4  . . . . . . . 3 3 . . . 3 2 . @ 1 1 . .
  //   y= 3  . . . . 3 3 3 3 3 3 3 3 3 3 3 . 1 1 . .
  //   y= 2  . . . . . . . 3 3 3 3 . . . . . 1 1 . .
  //   y= 1  . . . . . . 3 3 3 3 3 . . . . . . . . .
  //   y= 0  . . . . 2 2 2 2 2 2 2 2 2 2 . . . . . .
  {
    name: 'SKIPPING STONE',
    par: 3,
    size: { w: 20, d: 20 },
    terrain: ['00002222222222000000', '00000033333000000000', '00000003333000001100', '00003333333333301100', '00000003300032031100', '00000000100222001100', '00200000100222000000', '00000001010222000000', '00000000000222010000', '02221200220010010000', '00000022220022010000', '00000022220010010000', '00000022222210022030', '00000000222200010030', '02000330000000010030', '02000330002000022030', '02000330002220000030', '32300000000000000030', '32302222220000001030', '32300000000000021030'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 1, y: 19, dir: 'S' },
    targets: [{ x: 15, y: 4 }],
    fixed: [{ x: 1, y: 9, type: 'MIRROR', orient: '\\', secret: false }],
    tray: ['DIP', 'FLOOR', 'DIP', 'MIRROR'],
    intro: 'A FLOOR mirror lies flat in the ground. It never turns the beam - it only catches one that is already falling and throws it straight back up, still heading the same way. Send the beam down with a dip, then look for the bright dot where it touches the floor: that dot is the bounce.',
    solution: [{ x: 8, y: 9, type: 'DIP', orient: '\\' }, { x: 8, y: 7, type: 'FLOOR', orient: '/' }, { x: 8, y: 4, type: 'DIP', orient: '\\' }],
  },

  // 14. THE LOW ROAD  (20x20, par 3, seed 1406)
  //   y=19  1 1 1 1 . 3 3 3 3 . . . . 2 2 2 2 2 2 2
  //   y=18  1 1 1 1 . 1 1 1 1 . . @ . 2 . . . . . .
  //   y=17  . . . . . 1 1 1 1 . . . . 2 . . . . . .
  //   y=16  . . . . . 1 1 1 1 . . . . . . . . . . 3
  //   y=15  . . . . . 1 1 1 1 . . . . . . . . . . .
  //   y=14  . . 1 1 1 1 . . . . . . . . . . . . . .
  //   y=13  . . 1 1 1 1 . . . . . . . . . . . . . .
  //   y=12  . . 1 3 3 3 3 3 3 3 3 . . . . . . . . .
  //   y=11  . . . . . . . 3 3 3 3 . . . . . . . . .
  //   y=10  1 1 . . . F . . 3 3 3 . 1 1 1 1 . . . .
  //   y= 9  1 1 . . . . 3 A 3 3 . . . . . . . . . .
  //   y= 8  . . . . . . 1 . . . . . . . . . . . . .
  //   y= 7  . . . . . 1 . . . . . . . . 2 2 2 2 . .
  //   y= 6  . . . . . 2 . 3 . . . 3 . 2 2 2 2 2 . .
  //   y= 5  . . . . . 1 . 3 . . . 3 . 3 2 2 2 2 1 .
  //   y= 4  . . 3 3 . . 1 3 . . . 3 . 3 2 2 2 2 1 .
  //   y= 3  . . 3 3 . . 1 . . . . 3 . 3 . . . . 1 .
  //   y= 2  . . 3 3 . . . . 3 3 3 3 3 3 . . . . 1 .
  //   y= 1  . . 3 3 1 . 1 1 1 1 1 3 1 3 . . . . 1 .
  //   y= 0  . . . . . ^ . . . . . 3 . 3 . . . . . .
  {
    name: 'THE LOW ROAD',
    par: 3,
    size: { w: 20, d: 20 },
    terrain: ['00000200000303000000', '00331011111313000010', '00330000333333000010', '00330010000303000010', '00330013000303222210', '00000103000303222210', '00000203000302222200', '00000100000000222200', '00000010000000000000', '11000033330000000000', '11000200333011110000', '00000003333000000000', '00133333333000000000', '00111100000000000000', '00111100000000000000', '00000111100000000000', '00000111100000000003', '00000111100002000000', '11110111100002000000', '11110333300002222222'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 7, y: 9, levels: [0] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 5, y: 0, dir: 'N' },
    targets: [{ x: 11, y: 18 }],
    fixed: [{ x: 5, y: 10, type: 'DIP', orient: '/', secret: false }],
    tray: ['WEDGE', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 7, y: 10, type: 'WEDGE', orient: '\\' }, { x: 7, y: 7, type: 'MIRROR', orient: '\\' }, { x: 11, y: 7, type: 'MIRROR', orient: '/' }],
  },

  // 15. THREAD THE NEEDLE  (20x20, par 3, seed 1513)
  //   y=19  . . . @ 1 1 . 3 3 3 . . . . . . . . . .
  //   y=18  . . . 1 3 3 . 3 3 3 . . . . 3 3 . . . .
  //   y=17  1 1 1 1 3 3 . . 1 1 . . . . 3 3 . . . .
  //   y=16  1 3 3 O 3 3 . . . 1 1 . . . 3 3 . . . .
  //   y=15  1 1 1 . 2 . 3 3 . 1 1 . . . 3 3 . . . .
  //   y=14  1 1 1 . 2 . . . . 2 2 2 2 2 . . . . . .
  //   y=13  . . . 2 2 1 . . . . 2 . . . . . . . . .
  //   y=12  . . . . 2 . . . . . . . . . . . . . . .
  //   y=11  . . . . 1 . 3 3 3 3 1 . . . . . . . . .
  //   y=10  . . . . 1 3 3 3 3 3 1 . . . . . 3 3 2 2
  //   y= 9  . 2 . . 1 . . . . . . . . 2 2 2 2 . 2 2
  //   y= 8  . . . . 1 . . 1 F . 2 . . 2 2 2 2 . . .
  //   y= 7  . . . . . . . 1 . . . 2 2 2 2 2 2 2 2 2
  //   y= 6  . . . . . 1 1 1 . 1 1 1 1 1 1 . . . . .
  //   y= 5  . . . . . . . . . 1 1 1 1 . . 3 3 . . .
  //   y= 4  . . . . . . . . . . . . . . . 3 3 . . .
  //   y= 3  . 3 3 . . . . . . . . . . . . 3 3 . . .
  //   y= 2  . 3 3 . . . . . . . . . . . . 3 3 . . .
  //   y= 1  . 3 3 . . . . . . . . . . . . 3 3 . . .
  //   y= 0  . . . . 2 2 2 2 ^ 2 2 2 2 2 2 3 3 . . .
  {
    name: 'THREAD THE NEEDLE',
    par: 3,
    size: { w: 20, d: 20 },
    terrain: ['00002222022222233000', '03300000000000033000', '03300000000000033000', '03300000000000033000', '00000000000000033000', '00000000011110033000', '00000111011111100000', '00000001000222222222', '00001001002002222000', '02001000000002222022', '00001333331000003322', '00001033331000000000', '00002000000000000000', '00022100002000000000', '11102000022222000000', '11102033011000330000', '13333300011000330000', '11113300110000330000', '00013303330000330000', '00021103330000000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 3, y: 16, levels: [2] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 8, y: 0, dir: 'N' },
    targets: [{ x: 3, y: 19 }],
    fixed: [{ x: 8, y: 8, type: 'WEDGE', orient: '/', secret: false }],
    tray: ['DIP', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: 'The hole in this one is high up. Climb with a wedge, then level off with a dip so the beam is flying at the hole\'s own height when it arrives - the readout after FIRE tells you the height you actually got.',
    solution: [{ x: 10, y: 8, type: 'DIP', orient: '/' }, { x: 10, y: 13, type: 'MIRROR', orient: '\\' }, { x: 3, y: 13, type: 'MIRROR', orient: '\\' }],
  },

  // 16. STONE BRIDGE  (20x20, par 3, seed 1601)
  //   y=19  . . . . . . . 2 1 1 1 1 3 1 1 1 . . 3 3
  //   y=18  . 3 3 3 . . . 2 . . 2 . 3 3 3 3 3 2 2 2
  //   y=17  . 3 3 3 . . . 2 . . 2 . . . 1 1 2 2 2 2
  //   y=16  . 3 3 3 . . . . . . 2 . . . 1 1 . 1 . .
  //   y=15  . 3 3 3 . 2 2 . . . 2 . . . . . . 1 . .
  //   y=14  . 1 1 1 1 2 2 3 2 2 2 2 2 2 2 2 2 1 . .
  //   y=13  . . 2 2 . 2 2 . . 1 2 . 3 3 3 . . 1 . .
  //   y=12  . . . . . 2 2 . . 1 2 . 3 3 3 . . 1 . .
  //   y=11  . . . . . . . . . 1 2 . 3 3 3 3 . . . 1
  //   y=10  . . . . . . . . . 1 2 . 3 3 3 3 . 2 . .
  //   y= 9  . . . . . . . . . . . . F . . A . . . <
  //   y= 8  . . . . . . . . . . . . . 2 . 3 . 2 . .
  //   y= 7  . . . . . . . . . . . . . 2 . 3 . 2 . .
  //   y= 6  . . . . . . . . . . . . . 2 . . . 2 . .
  //   y= 5  . . . . . . . . . . . . . 2 . . . 2 . .
  //   y= 4  . . . . . . . . . . . 2 . 2 2 . . 2 . .
  //   y= 3  1 1 1 . . . . . . 3 1 1 . 2 2 . . 2 2 2
  //   y= 2  1 1 1 . . . . . . 3 3 3 3 3 3 3 3 . . .
  //   y= 1  . . . . . . . . . 2 . . . . . . . . . .
  //   y= 0  @ . . . 2 3 2 . . 3 . . . . . . . . . .
  {
    name: 'STONE BRIDGE',
    par: 3,
    size: { w: 20, d: 20 },
    terrain: ['30002320030000000000', '00000000020000000000', '11100000033333333000', '11100000031102200222', '00000000000202200200', '00000000000002000200', '00000000000002000200', '00000000000002030200', '00000000000002030200', '00000000000000030000', '00000000012033330200', '00000000012033330001', '00000220012033300100', '00220220012033300100', '01111223222222222100', '03330220002000000100', '03330000002000110100', '03330002002000112222', '03330002002033333222', '00000002111131110033'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 15, y: 9, levels: [0] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 19, y: 9, dir: 'W' },
    targets: [{ x: 0, y: 0 }],
    fixed: [{ x: 12, y: 9, type: 'MIRROR', orient: '/', secret: false }],
    tray: ['WEDGE', 'DIP', 'MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 12, y: 3, type: 'WEDGE', orient: '/' }, { x: 9, y: 3, type: 'DIP', orient: '/' }, { x: 9, y: 0, type: 'MIRROR', orient: '/' }],
  },

  // 17. THE SKIMMING STONE  (22x22, par 3, seed 1705)
  //   y=21  . . 3 . . . . . . . . 3 . . . . . . . 3 . .
  //   y=20  . . 3 . . . . . . . . 1 . . . . . . . . . .
  //   y=19  . . 3 . . . . . . . . 1 . . . 3 3 3 3 3 3 3
  //   y=18  . . 3 2 . . . . @ . 3 3 3 3 2 . 3 3 . . . .
  //   y=17  . . 3 . 2 . . . . . . 1 . . 3 3 . 3 . . 2 2
  //   y=16  . . . . 2 . . . 2 2 2 2 2 2 3 3 . 3 . . . .
  //   y=15  2 . . . 2 . . . . . . . . . . . 3 . . . . .
  //   y=14  2 . . 1 2 . . . . . . . . . 1 . 2 . . . . .
  //   y=13  2 . 2 2 2 . . . . . . . . . 1 . . . . . . .
  //   y=12  2 . 2 2 2 2 2 2 2 2 . . . . 1 2 . 1 . . . .
  //   y=11  2 . . . 2 2 2 2 2 . . 2 . F 1 1 3 1 . . 1 1
  //   y=10  2 . . 2 2 2 2 2 2 2 2 . 2 . 1 . . 1 . . . .
  //   y= 9  . . . 2 2 2 2 2 2 2 2 . 2 . 1 . . 1 . . . .
  //   y= 8  . . . 2 2 2 2 2 2 2 2 1 2 . 1 . . 1 . . . .
  //   y= 7  . . . . 2 . . 2 2 2 2 2 2 . 1 . . 1 . . . .
  //   y= 6  3 3 . . 2 . . . . 3 3 1 3 . 1 . . 2 2 . . .
  //   y= 5  3 3 . . . . . . . 3 3 2 3 . 1 2 2 2 2 2 2 .
  //   y= 4  3 3 . . . . . . . 3 3 . 3 . . . . . . . . .
  //   y= 3  . . . . . . . . . 3 3 . 3 . . . . . . . . .
  //   y= 2  . . . . . . . . . . . . . . . . . 1 1 1 1 1
  //   y= 1  . . . . . . . . . . . . . . . . . . . . . .
  //   y= 0  . . . . . . 3 3 3 3 3 ^ . . . . . . . . . .
  {
    name: 'THE SKIMMING STONE',
    par: 3,
    size: { w: 22, d: 22 },
    terrain: ['0000003333320000000000', '0000000000000000000000', '0000000000000000011111', '0000000003303000000000', '3300000003303000000000', '3300000003323012222220', '3300200003313010022000', '0000200222222010010000', '0002222222212010010000', '0002222222202010010000', '2002222222202010010000', '2000222220020011310011', '2022222222000012010000', '2022200000000010000000', '2001200000000010200000', '2000200000000000300000', '0000200022222233030000', '0030200000010033030022', '0032000030333320330000', '0030000000010003333333', '0030000000010000000000', '0030000000030000000300'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 11, y: 0, dir: 'N' },
    targets: [{ x: 8, y: 18 }],
    fixed: [{ x: 13, y: 11, type: 'FLOOR', orient: '/', secret: false }],
    tray: ['DIP', 'DIP', 'MIRROR', 'FLOOR'],
    intro: '',
    solution: [{ x: 11, y: 11, type: 'DIP', orient: '/' }, { x: 16, y: 11, type: 'DIP', orient: '/' }, { x: 16, y: 18, type: 'MIRROR', orient: '\\' }],
  },

  // 18. SECRET STEPS  (22x22, par 4, seed 1802)
  //   y=21  . 1 . . . . . v . . . . . . 2 2 2 2 2 . . .
  //   y=20  . . . . . . . . 1 1 1 1 . 3 3 3 3 . . . . .
  //   y=19  . . . . . . . . 1 1 1 1 . 3 3 3 3 . . . . .
  //   y=18  . . . . . . . . 1 1 1 3 3 2 2 . . . . . 3 3
  //   y=17  . . . . . . . . 1 1 1 3 3 2 2 1 1 . . 3 3 3
  //   y=16  . 2 2 2 2 2 2 . 2 2 2 3 3 1 1 3 3 1 1 . . .
  //   y=15  . 2 . . . . . . . . . 3 3 1 1 3 3 1 1 . . .
  //   y=14  . 2 . . . . . . 3 . . . . 1 1 3 3 1 1 2 2 2
  //   y=13  . 2 . . . . . . 3 . 2 2 2 2 2 2 2 2 2 . . .
  //   y=12  . 2 . . . . . . 3 3 . . 2 3 3 . . . . . . .
  //   y=11  . 2 . . . . . F . 2 . . . . . . . . . . . .
  //   y=10  . . . . . . . . . 1 . . . . 3 . . . . . . .
  //   y= 9  . . . . . . . . . 1 . . . . 2 . . . . . 3 3
  //   y= 8  . . . . . . . . 3 3 . . . . 2 . . . . . 3 3
  //   y= 7  . 1 1 1 . . . . . 1 . 2 2 2 . . . . . 1 . 2
  //   y= 6  . 1 1 1 2 . . . . 1 . 2 2 2 3 1 1 @ . 1 . 2
  //   y= 5  . 1 1 1 1 . . . . 1 . 2 2 2 . . . . . 1 . 2
  //   y= 4  . 1 1 1 1 . . . . 1 . . . . . . . . . 1 . 2
  //   y= 3  . 1 1 1 1 . . . . . . . . . 3 . . 1 1 1 . 2
  //   y= 2  . . . . . . . . . . . . . . . . . 1 1 1 . 2
  //   y= 1  . . . . . . . . . . . . . . . 3 3 . . . . 2
  //   y= 0  . . . . . . . . . . . . . . . 2 . . . . . 2
  {
    name: 'SECRET STEPS',
    par: 4,
    size: { w: 22, d: 22 },
    terrain: ['0000000000000002000002', '0000000000000003300002', '0000000000000000011102', '0111100000000030011102', '0111100001000000000102', '0111100001022200000102', '0111200001022231100102', '0111000001022200000102', '0000000033000020000033', '0000000001000020000033', '0000000001000030000000', '0200000002000000000000', '0200000033002330000000', '0200000030222222222000', '0200000030000113311222', '0200000000033113311000', '0222222022233113311000', '0000000011133221100333', '0000000011133220000033', '0000000011110333300000', '0000000011110333300000', '0100000000000022222000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 7, y: 21, dir: 'S' },
    targets: [{ x: 17, y: 6 }],
    fixed: [{ x: 7, y: 11, type: 'WEDGE', orient: '\\', secret: true }],
    tray: ['MIRROR', 'DIP', 'MIRROR', 'DIP', 'MIRROR'],
    intro: '',
    solution: [{ x: 9, y: 11, type: 'MIRROR', orient: '/' }, { x: 9, y: 12, type: 'DIP', orient: '/' }, { x: 14, y: 12, type: 'MIRROR', orient: '\\' }, { x: 14, y: 6, type: 'DIP', orient: '\\' }],
  },

  // 19. THE HIGH WINDOW  (22x22, par 4, seed 1907)
  //   y=21  . . . . 1 . . . . . . . 3 3 3 3 3 3 3 3 3 3
  //   y=20  . 2 2 . 1 . . . . . . . 3 . . . . . . . . .
  //   y=19  . . . . 1 . . . . . . 3 3 . . . . . . . . .
  //   y=18  . . . . . . . . . . . 3 3 . . . . . . . . .
  //   y=17  . . . . . . . . . . 3 3 3 . . . . . . . . 3
  //   y=16  . . . . . . . . . . 3 3 3 . . . . . . . . .
  //   y=15  1 1 1 . . . . . . . 3 3 3 . . . . . . . . .
  //   y=14  1 1 1 2 2 2 2 2 . . 3 3 3 3 3 3 . . 3 3 3 3
  //   y=13  . . . . . 2 . . . . 3 3 3 3 3 3 . 2 2 2 2 .
  //   y=12  3 3 3 3 3 3 . . . 2 . 1 2 2 2 2 3 . . . . .
  //   y=11  . 3 . . . 2 . . . . 3 . . . 3 . 3 . . . . .
  //   y=10  > . . . . . . . . F 3 . . . 3 . 3 . . . . .
  //   y= 9  . 3 . . . 2 1 . . . . 2 2 2 3 . 2 2 2 . . .
  //   y= 8  . . . . . 2 1 . 2 2 2 2 2 2 3 . 1 . 3 . . .
  //   y= 7  . . . . . . . 1 1 1 . . . . 3 2 . . . 2 . .
  //   y= 6  . . . . . . . 1 1 1 . . . . 3 . . . 3 . . .
  //   y= 5  2 2 . . . . . 1 1 1 1 1 1 . 3 1 1 3 3 O 3 3
  //   y= 4  2 2 . . . . . . . 1 1 1 1 . 3 . . . . 2 . .
  //   y= 3  2 2 . . . . . . . 1 1 1 2 2 3 2 2 3 2 2 . .
  //   y= 2  . . . . . . . . . . . . . . 3 . . . . 1 . .
  //   y= 1  . . . . . . . . . . . . 2 2 . . . . . . . .
  //   y= 0  1 1 1 1 1 1 1 1 . . . 1 . . . . . . . @ . .
  {
    name: 'THE HIGH WINDOW',
    par: 4,
    size: { w: 22, d: 22 },
    terrain: ['1111111100010000000200', '0000000000002200000000', '0000000000000030000100', '2200000001112232232200', '2200000001111030000200', '2200000111111031133333', '0000000111000030003000', '0000000111000032000200', '0000021022222230103000', '0300021000022230222000', '0000000000300030300000', '0300020000300030300000', '3333330002012222300000', '0000020000333333022220', '1112222200333333003333', '1110000000333000000000', '0000000000333000000000', '0000000000333000000003', '0000000000033000000000', '0000100000033000000000', '0220100000003000000000', '0000100000003333333333'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    openings: [{ x: 19, y: 5, levels: [2] }],   // DESIGN.md 13: these columns are NOT solid at these levels
    emitter: { x: 0, y: 10, dir: 'E' },
    targets: [{ x: 19, y: 0 }],
    fixed: [{ x: 9, y: 10, type: 'WEDGE', orient: '/', secret: false }],
    tray: ['DIP', 'MIRROR', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 9, y: 12, type: 'DIP', orient: '/' }, { x: 15, y: 12, type: 'MIRROR', orient: '\\' }, { x: 15, y: 7, type: 'MIRROR', orient: '\\' }, { x: 19, y: 7, type: 'MIRROR', orient: '\\' }],
  },

  // 20. HIGH ROAD LOW ROAD  (22x22, par 4, seed 2003)
  //   y=21  . . 3 . . . . . . . . . . . . . . . . . . .
  //   y=20  . . 3 2 . . . . . . . . . . 2 2 2 2 2 2 2 2
  //   y=19  . . 3 . . . . . . . . 2 2 2 2 . . . . . . .
  //   y=18  . . 3 . . . . . . 2 2 2 @ 2 2 . . . . . . .
  //   y=17  . . 3 . 2 2 2 2 . 2 2 2 . 2 2 . . . . . . .
  //   y=16  . . 3 . 2 2 2 2 . 2 2 2 . . . . . . . . . .
  //   y=15  . . . . . . . . . 2 2 3 . . . . 3 3 3 3 3 3
  //   y=14  . . . . 2 2 2 2 2 2 2 3 . 2 2 1 1 1 1 1 1 1
  //   y=13  . . 1 3 3 3 3 3 3 3 3 3 . . . . . . . . . .
  //   y=12  . . 1 2 . . . 1 . . 3 3 . . . . . . . . . .
  //   y=11  . . 1 2 . . . 1 . . 3 3 . 1 1 1 1 1 1 1 3 3
  //   y=10  1 1 1 2 . . . 1 . . 3 3 . . . . . . . . . .
  //   y= 9  1 1 1 2 . . . 1 . . 1 3 . . . 1 1 1 1 . . .
  //   y= 8  1 1 1 2 . . . 1 . . 1 3 3 3 3 @ . 3 1 . . .
  //   y= 7  1 1 1 2 . . . 1 1 1 1 3 1 1 1 . . 2 1 . . .
  //   y= 6  . . . . . . . 1 . . 1 3 . . . . 1 1 3 . . .
  //   y= 5  . . . . . . . . . . 1 . . . . . . . . . . .
  //   y= 4  . . . . . . . . . . 1 . . . . . . . . . . .
  //   y= 3  . . . . . . . . . . . . . . . . 1 1 1 . . .
  //   y= 2  . . . . . . . . . . . . . . . F . . . . . <
  //   y= 1  . . . . . . . 3 3 3 3 . . . . . 1 1 1 . . .
  //   y= 0  . . . . . . . 3 3 3 3 . . . . . 1 1 1 . . .
  {
    name: 'HIGH ROAD LOW ROAD',
    par: 4,
    size: { w: 22, d: 22 },
    terrain: ['0000000333300000111000', '0000000333300000111000', '0000000000000000000000', '0000000000000000111000', '0000000000100000000000', '0000000000100000000000', '0000000100130000113000', '1112000111131110021000', '1112000100133333031000', '1112000100130001111000', '1112000100330000000000', '0012000100330111111133', '0012000100330000000000', '0013333333330000000000', '0000222222230221111111', '0000000002230000333333', '0030222202220000000000', '0030222202220220000000', '0030000002223220000000', '0030000000022220000000', '0032000000000022222222', '0030000000000000000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 21, y: 2, dir: 'W' },
    targets: [{ x: 15, y: 8 }, { x: 12, y: 18 }],
    fixed: [{ x: 15, y: 2, type: 'MIRROR', orient: '\\', secret: false }],
    tray: ['WEDGE', 'WEDGE', 'DIP', 'MIRROR', 'MIRROR'],
    intro: '',
    solution: [{ x: 15, y: 7, type: 'WEDGE', orient: '/' }, { x: 17, y: 7, type: 'WEDGE', orient: '/' }, { x: 17, y: 8, type: 'DIP', orient: '\\' }, { x: 12, y: 8, type: 'MIRROR', orient: '\\' }],
  },

  // 21. THE LONG WAY ROUND  (24x24, par 5, seed 2103)
  //   y=23  . . . . . 2 2 . 1 3 3 2 2 . . . . 1 . . . . . .
  //   y=22  . . . . . . . . 2 . . . . . . . . 1 . . 1 1 1 1
  //   y=21  . . . . . . . . 2 . . . . . . . . 1 . . . 2 2 2
  //   y=20  . . . . . . . . 2 . . . . . F . . . . . . . . <
  //   y=19  . . . . 1 1 1 . 3 3 3 . . . . . . . . . . . . .
  //   y=18  . . . . 1 1 1 . 3 3 3 . . . . . . . . . . . . .
  //   y=17  . . . . 1 1 1 . . 1 . . 2 . . . . . . . . 2 2 2
  //   y=16  . . . . . . . 2 2 . . . . . . . . . . . . . . .
  //   y=15  . . . 3 3 3 3 3 . 3 3 3 3 . . 1 1 1 1 1 1 1 1 1
  //   y=14  . . . . . . . 3 . . . . 2 . . 1 1 1 1 . . 2 2 2
  //   y=13  . . . 2 2 . . 2 3 3 3 2 . . . . 3 3 3 3 . . . .
  //   y=12  . . . . . . . 3 3 3 3 . . . . 2 . 3 3 3 3 3 3 .
  //   y=11  . . . . . . . 3 3 3 3 . . . . 2 2 3 3 3 3 3 3 .
  //   y=10  . . @ 3 3 . . 3 3 3 3 . . . . . . 3 3 3 3 3 3 .
  //   y= 9  . . . 2 3 . . . . . . 1 . . . . 2 2 2 2 2 2 . .
  //   y= 8  . . 2 2 . . . . 1 1 1 . 1 1 1 1 1 2 2 2 2 2 3 3
  //   y= 7  . 1 1 2 . . . . 1 1 1 . . . . . . 2 2 2 2 2 . .
  //   y= 6  . 1 1 2 . 2 2 . . . . . . . . . . 2 2 2 2 2 2 .
  //   y= 5  . 1 1 2 . . . . . . . . . . . . . . . 2 . 2 2 .
  //   y= 4  . 1 1 2 3 3 3 . . . . . . . . . . . . 2 . 2 2 .
  //   y= 3  . . 1 2 3 3 3 . . . . . . . . . . . 2 2 3 3 3 .
  //   y= 2  . . . . . . . . . . . . . . . . . . 2 2 3 3 3 .
  //   y= 1  . . . . . . . . . . . . . . . . . . 2 2 3 3 3 .
  //   y= 0  . . . . . . . . . . . . . . . 2 2 2 2 2 2 . . .
  {
    name: 'THE LONG WAY ROUND',
    par: 5,
    size: { w: 24, d: 24 },
    terrain: ['000000000000000222222000', '000000000000000000223330', '000000000000000000223330', '001233300000000000223330', '011233300000000000020220', '011200000000000000020220', '011202200000000002222220', '011200001110000002222200', '002200001110111112222233', '000230000001000022222200', '003330033330000003333330', '000000033330000223333330', '000000033330000203333330', '000220023332000033330000', '000000030000200111100222', '000333330333300111111111', '000000022000000000000000', '000011100100200000000222', '000011103330000000000000', '000011103330000000000000', '000000002000000000000000', '000000002000000001000222', '000000002000000001001111', '000002201332200001000000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 23, y: 20, dir: 'W' },
    targets: [{ x: 2, y: 10 }],
    fixed: [{ x: 14, y: 20, type: 'MIRROR', orient: '/', secret: false }],
    tray: ['WEDGE', 'MIRROR', 'DIP', 'MIRROR', 'MIRROR', 'MIRROR'],
    intro: '',
    dark: true,   // DESIGN.md 15: the board is drawn only where the beam has been
    solution: [{ x: 14, y: 14, type: 'WEDGE', orient: '/' }, { x: 12, y: 14, type: 'MIRROR', orient: '\\' }, { x: 12, y: 15, type: 'DIP', orient: '\\' }, { x: 7, y: 15, type: 'MIRROR', orient: '/' }, { x: 7, y: 10, type: 'MIRROR', orient: '/' }],
  },

  // 22. STONE SKIPPING  (24x24, par 4, seed 2221)
  //   y=23  . . . 3 . . 1 . . . . . . . . . . . . . 3 2 2 .
  //   y=22  . . . 3 . . 1 . . . . . . . 2 2 2 2 . . 3 2 2 .
  //   y=21  . . . 3 . . 1 . . . . . . . 2 2 2 2 . . 3 2 2 .
  //   y=20  . . . 3 . . . . . . . . . . . 2 2 2 . . 3 . . .
  //   y=19  . . . . . . . . . . . . . . . . . . . . 3 . . .
  //   y=18  . . . . . . . . . . . 3 3 . . . . . . . 2 2 . .
  //   y=17  1 . . . . . . . . . . 3 3 . . . . . . . . . . .
  //   y=16  1 . . . . . . . . . . 3 3 2 . . . . . . . . . <
  //   y=15  1 . . . . . 2 2 . . . 3 3 . 2 3 . . 2 . . . 2 2
  //   y=14  1 . . . . . . . . . . 3 3 F 2 3 . . 2 . . . . .
  //   y=13  . . . . . . . . . . . 1 . 1 2 3 . . 2 . . . . .
  //   y=12  . . . . . . . . . . . 1 . 1 2 3 . . 2 2 . . . .
  //   y=11  . . . . . . . . 3 . 3 3 2 3 3 2 2 2 2 2 . . . .
  //   y=10  . . . . . . . . 1 1 . 1 3 3 3 . . . 2 3 3 3 3 .
  //   y= 9  . . . 2 . . . . 1 1 . 1 3 3 3 . 1 1 2 3 3 3 3 .
  //   y= 8  1 1 1 1 1 1 1 1 F 1 1 1 . . 2 2 2 2 2 2 2 2 2 2
  //   y= 7  . . . . . . . . 1 1 . 1 . . 2 . 1 1 2 . . . . .
  //   y= 6  . . . . . 2 2 2 1 1 . 1 . . 2 . . . 2 . . . . .
  //   y= 5  @ . 3 2 3 2 . . 3 2 2 2 2 2 2 2 2 2 2 2 . . . .
  //   y= 4  . . . . . 2 2 2 2 1 . 2 . . . 3 3 3 1 1 . . . .
  //   y= 3  . . . . . 1 1 . . . . . . . . 3 3 3 1 1 . . . .
  //   y= 2  . . . . . 1 1 . . . . . . . . . 1 1 . . 2 2 2 2
  //   y= 1  . . . . . 1 1 . . . . . . . . . 1 1 . 2 . . . .
  //   y= 0  . . . . . 3 3 3 3 3 3 3 3 3 3 2 2 1 . . . . . .
  {
    name: 'STONE SKIPPING',
    par: 4,
    size: { w: 24, d: 24 },
    terrain: ['000003333333333221000000', '000001100000000011020000', '000001100000000011002222', '000001100000000333110000', '000002222102000333110000', '303232003222222222220000', '000002221101002000200000', '000000001101002011200000', '111111110111002222222222', '000200001101333011233330', '000000001101333000233330', '000000003033233222220000', '000000000001012300220000', '000000000001012300200000', '100000000003302300200000', '100000220003302300200022', '100000000003320000000002', '100000000003300000000000', '000000000003300000002200', '000000000000000000003000', '000300000000000222003000', '000300100000002222003220', '000300100000002222003220', '000300100000000000003220'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 23, y: 16, dir: 'W' },
    targets: [{ x: 0, y: 5 }],
    fixed: [{ x: 13, y: 14, type: 'FLOOR', orient: '/', secret: false }, { x: 8, y: 8, type: 'FLOOR', orient: '/', secret: false }],
    tray: ['DIP', 'DIP', 'DIP', 'DIP', 'MIRROR'],
    intro: '',
    dark: true,   // DESIGN.md 15: the board is drawn only where the beam has been
    solution: [{ x: 13, y: 16, type: 'DIP', orient: '/' }, { x: 13, y: 11, type: 'DIP', orient: '/' }, { x: 8, y: 11, type: 'DIP', orient: '/' }, { x: 8, y: 5, type: 'DIP', orient: '/' }],
  },

  // 23. SUMMIT  (24x24, par 5, seed 2324)
  //   y=23  . . . . . . . . . 3 . . . . . . 1 1 1 1 . . . .
  //   y=22  > . . . . . . . . . F . . . . . 1 1 1 1 . . . .
  //   y=21  . . . . . . . 3 3 3 . . . . . . 1 1 1 1 . . . .
  //   y=20  . . 3 3 3 3 . . . 3 2 . . . . 1 1 . . . . . . .
  //   y=19  . . 3 3 3 3 . . . 3 . . . . . 1 1 . . . . . 3 .
  //   y=18  . . . . . . . . . 2 . . 3 . . 1 . . . . . . . .
  //   y=17  . . . . . . . . . @ 1 . 3 3 3 3 3 3 3 3 3 3 3 3
  //   y=16  . . . . . . . . . 3 1 . 3 2 . 1 . . . . . . . .
  //   y=15  . . . . . . . . . 3 3 3 . . . 3 . . 2 2 . . . 2
  //   y=14  . . . . . . . . . . 1 2 3 2 2 2 . . . . . . . .
  //   y=13  . . . . 1 . . . 3 3 3 3 3 3 3 2 3 3 2 . . 3 3 3
  //   y=12  . . . . 1 . . . . . 1 . 3 . . 2 2 2 2 . . 3 3 3
  //   y=11  . . . . 1 . . . . . 1 . 3 . . 2 . 1 2 1 1 3 3 3
  //   y=10  . . . . 1 . . . . . . . 3 3 3 3 . . @ 1 1 1 1 .
  //   y= 9  . . . . . . . . 1 . . . 3 3 3 . . . . 1 1 1 1 .
  //   y= 8  . . . . . . . . 1 . . . 3 3 3 . . . . 1 1 1 1 .
  //   y= 7  . . . . . . . . 1 . . . 3 . . . . . . . . 1 1 .
  //   y= 6  . . . 1 1 1 2 2 2 2 2 2 2 2 2 2 . . . . . 1 1 .
  //   y= 5  . . . 1 1 1 . . 1 . . . . . . . . . . . . 1 1 .
  //   y= 4  . . . . . . . 3 1 . . . . . . . . 1 3 3 . . . .
  //   y= 3  . 2 2 2 . . . . 1 . . . . . . . . 1 1 1 . . . .
  //   y= 2  . 2 2 2 1 1 1 1 1 1 1 1 1 1 3 . . 2 2 2 . . . .
  //   y= 1  . 2 2 2 . . . . 1 . . . . . . . . 2 2 2 . . . .
  //   y= 0  2 2 2 2 2 2 2 2 2 . . . . . . . . . . . . . . .
  {
    name: 'SUMMIT',
    par: 5,
    size: { w: 24, d: 24 },
    terrain: ['222222222000000000000000', '022200001000000002220000', '022211111111113002220000', '022200001000000001110000', '000000031000000001330000', '000111001000000000000110', '000111222222222200000110', '000000001000300000000110', '000000001000333000011110', '000000001000333000011110', '000010000000333300011110', '000010000010300201211333', '000010000010300222200333', '000010003333333233200333', '000000000012322200000000', '000000000333000300220002', '000000000310320100000000', '000000000310333333333333', '000000000200300100000000', '003333000300000110000030', '003333000320000110000000', '000000033300000011110000', '000000000000000011110000', '000000000300000011110000'], // terrain[y][x], y = 0 is the SOUTH row (reverse of the map above)
    emitter: { x: 0, y: 22, dir: 'E' },
    targets: [{ x: 9, y: 17 }, { x: 18, y: 10 }],
    fixed: [{ x: 10, y: 22, type: 'WEDGE', orient: '\\', secret: true }],
    tray: ['MIRROR', 'DIP', 'MIRROR', 'MIRROR', 'DIP', 'MIRROR'],
    intro: '',
    dark: true,   // DESIGN.md 15: the board is drawn only where the beam has been
    solution: [{ x: 10, y: 20, type: 'MIRROR', orient: '/' }, { x: 9, y: 20, type: 'DIP', orient: '/' }, { x: 9, y: 15, type: 'MIRROR', orient: '\\' }, { x: 15, y: 15, type: 'MIRROR', orient: '\\' }, { x: 15, y: 10, type: 'DIP', orient: '\\' }],
  }
  ];
}));
